# Generated by Django 5.0.6 on 2024-05-16 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_announcement_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone_number',
            options={'verbose_name_plural': 'сохраненные вторичный номеры'},
        ),
        migrations.DeleteModel(
            name='announcement_recommendations',
        ),
    ]
