# Generated by Django 5.0.6 on 2024-05-16 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_alter_phone_number_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='floor',
            field=models.ForeignKey(blank=True, default='Provider Data', null=True, on_delete=django.db.models.deletion.CASCADE, to='announcements.floor', verbose_name='этаж'),
        ),
    ]
