# Generated by Django 5.0.6 on 2024-05-18 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_remove_announcement_title_alter_announcement_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='apartment_images',
            options={'verbose_name_plural': 'Загруженные Фотки'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name_plural': 'Этажи'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='floor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='announcements.floor', verbose_name='этаж'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='landmark',
            field=models.CharField(max_length=40, verbose_name='Ориентир'),
        ),
    ]
