# Generated by Django 5.0.6 on 2024-05-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='location',
        ),
    ]
